'use client';
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowUpRight, BookUser, Check, ChevronDown, ChevronRight, CircleHelp, Copy, LayoutGrid, LoaderCircle, LogOut, Megaphone, Menu, MessageCircle, Paperclip, Plus, QrCode, RefreshCw, Search, Send, Settings2, ShieldCheck, Smartphone, Users, Wifi, X } from 'lucide-react';
import type { Contact, DashboardData, WhatsAppNumber } from '@/lib/types';
import { InboxPanel } from '@/components/inbox-panel';
import { CampaignsPanel } from '@/components/campaigns-panel';
import { countryCodes } from '@/lib/phone';
import { mediaAccept, uploadMedia } from '@/lib/media';

type Modal = 'number' | 'workspace' | 'invite' | 'pair' | 'message' | null;
export function Dashboard({ initial }: { initial: DashboardData }) {
  const [workspaces, setWorkspaces] = useState(initial.workspaces);
  const [active, setActive] = useState(initial.workspaces[0]?.id ?? '');
  const [numbers, setNumbers] = useState(initial.numbers);
  const [members, setMembers] = useState(initial.members);
  const [tab, setTab] = useState('overview');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [modal, setModal] = useState<Modal>(null);
  const [selected, setSelected] = useState<WhatsAppNumber | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState(initial.error ?? '');
  const [qr, setQr] = useState('');
  const [invite, setInvite] = useState('');
  const [mobileOpen, setMobileOpen] = useState(false);
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [contactNumberId, setContactNumberId] = useState('');
  const [contactsLoaded, setContactsLoaded] = useState(false);
  const [contactQuery, setContactQuery] = useState('');
  const [selectedContacts, setSelectedContacts] = useState<string[]>([]);
  const workspace = workspaces.find(w => w.id === active);
  const canManage = workspace?.role === 'owner' || workspace?.role === 'admin';
  const current = numbers.filter(n => n.workspace_id === active);
  const connected = current.filter(n => n.state === 'open').length;
  const visible = current.filter(n => `${n.label} ${n.phone ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'connected' ? n.state === 'open' : n.state !== 'open')));
  const connectedNumbers = current.filter(n => n.state === 'open');
  const visibleContacts = contacts.filter(contact => `${contact.name} ${contact.phone}`.toLowerCase().includes(contactQuery.toLowerCase()));
  const activeRef = useRef(active);
  activeRef.current = active;
  async function request(path: string, body?: unknown) {
    const response = await fetch(path, { method: body ? 'POST' : 'GET', headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined });
    const data = await response.json();
    if (!response.ok) throw new Error(data.error ?? 'Something went wrong. Please try again.');
    return data;
  }
  async function refresh(workspaceId = active) {
    if (!workspaceId) return;
    const data = await request(`/api/workspaces?id=${encodeURIComponent(workspaceId)}`);
    if (activeRef.current !== workspaceId) return;
    setNumbers(prev => [...prev.filter(n => n.workspace_id !== workspaceId), ...data.numbers]);
    setMembers(data.members);
    if (data.warning) setNotice(data.warning);
  }
  useEffect(() => { if (active) { setMembers([]); setContacts([]); setContactsLoaded(false); setContactNumberId(''); setSelectedContacts([]); refresh(active).catch(e => setNotice(e.message)); } }, [active]); // eslint-disable-line react-hooks/exhaustive-deps
  async function run(action: () => Promise<void>) { setBusy(true); setNotice(''); try { await action(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Please try again.'); } finally { setBusy(false); } }
  function open(next: Modal, number?: WhatsAppNumber) { setSelected(number ?? null); setQr(''); setInvite(''); setModal(next); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const fields = Object.fromEntries(form);
    await run(async () => {
      if (modal === 'workspace') { const data = await request('/api/workspaces', { name: fields.name }); setWorkspaces(prev => [...prev, data.workspace]); setActive(data.workspace.id); }
      if (modal === 'number') { const data = await request('/api/numbers', { action: 'create', workspaceId: active, label: fields.label }); await refresh(); if (data.warning) setNotice(data.warning); }
      if (modal === 'invite') { const data = await request('/api/team', { action: 'invite', workspaceId: active, email: fields.email, role: fields.role }); setInvite(`${window.location.origin}/invite?token=${data.token}`); return; }
      if (modal === 'message') { const file=form.get('media'); const media=file instanceof File&&file.size?await uploadMedia(active,file):undefined; await request('/api/numbers', { action: 'send', workspaceId: active, numberId: selected?.id, phone: fields.phone, countryCode: fields.countryCode, text: fields.text, media }); setNotice('Message accepted by WhatsApp.'); }
      setModal(null);
    });
  }
  async function pair() { await run(async () => { const data = await request('/api/numbers', { action: 'connect', workspaceId: active, numberId: selected?.id }); if (data.base64) setQr(data.base64); else setNotice(data.connected ? 'This number is already connected. Close this panel and refresh.' : 'QR code is preparing. Try again in a few seconds.'); }); }
  async function loadContacts(numberId = contactNumberId) { if (!numberId) return; await run(async () => { const data = await request(`/api/contacts?workspaceId=${encodeURIComponent(active)}&numberId=${encodeURIComponent(numberId)}`); setContacts(data.contacts); setContactsLoaded(true); setSelectedContacts([]); }); }
  function nav(name: string) {
    setTab(name);
    setMobileOpen(false);
    setQuery('');
    window.requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: 'smooth' }));
  }
  return <div className="app-shell">
    {mobileOpen && <button className="mobile-overlay" aria-label="Close menu" onClick={() => setMobileOpen(false)} />}
    <aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}>
      <a href="/" className="brand"><span className="brand-icon"><MessageCircle size={23} strokeWidth={2.5}/></span>v connect<span className="brand-dot">.</span></a>
      <div className="workspace-picker"><span className="workspace-avatar">{workspace?.name.slice(0, 1) ?? 'W'}</span><label><span className="eyebrow">WORKSPACE</span><select aria-label="Current workspace" value={active} onChange={e => setActive(e.target.value)}>{workspaces.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}{!workspaces.length && <option value="">Create a workspace</option>}</select></label><ChevronDown size={15}/></div>
      <div className="nav-label">WORKSPACE</div>
      <nav aria-label="Main navigation">{[{ id: 'overview', label: 'Overview', icon: LayoutGrid }, { id: 'inbox', label: 'Inbox', icon: MessageCircle }, { id: 'numbers', label: 'WhatsApp numbers', icon: Smartphone }, { id: 'contacts', label: 'Contacts', icon: BookUser }, { id: 'broadcasts', label: 'Broadcasts', icon: Megaphone }, { id: 'team', label: 'Team members', icon: Users }, { id: 'settings', label: 'Settings', icon: Settings2 }].map(item => <button key={item.id} className={`nav-item ${tab === item.id ? 'active' : ''}`} onClick={() => nav(item.id)}><item.icon size={19}/>{item.label}{item.id === 'numbers' && <span className="nav-count">{current.length}</span>}</button>)}</nav>
      <button className="new-workspace" onClick={() => open('workspace')}><Plus size={17}/>Create workspace</button>
      <div className="sidebar-bottom"><div className="privacy-card"><ShieldCheck size={21}/><strong>Your workspace, private.</strong><p>Numbers and access stay separate across your teams.</p></div><button className="help-link" onClick={() => nav('help')}><CircleHelp size={18}/>Help & getting started<ArrowUpRight size={15}/></button><div className="profile"><span className="profile-avatar">{initial.user.email.slice(0, 1).toUpperCase()}</span><span><strong>{initial.user.email.split('@')[0]}</strong><small>{workspace?.role ?? 'Workspace member'}</small></span><button className="icon-button" aria-label="Sign out" onClick={() => run(async () => { await request('/api/auth', { action: 'signout' }); window.location.href = '/login'; })}><LogOut size={17}/></button></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={22}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{tab === 'numbers' ? 'WhatsApp numbers' : tab === 'contacts' ? 'Contacts' : tab === 'broadcasts' ? 'Broadcasts' : tab === 'team' ? 'Team members' : tab === 'help' ? 'Getting started' : tab === 'settings' ? 'Settings' : 'Overview'}</strong></div><div className="topbar-right"><span className="private-label"><ShieldCheck size={15}/>Private workspace</span><span className="mini-avatar">{initial.user.email.slice(0, 1).toUpperCase()}</span></div></header>
      <main id="main-content" data-tab={tab}>
        {notice && <div className="notice" role="status"><span>{notice}</span><button className="icon-button" aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={17}/></button></div>}
        <div className="page-heading"><div><div className="section-kicker">{workspace?.name ?? 'YOUR WORKSPACE'}</div><h1>{tab === 'overview' ? 'Your workspace at a glance.' : tab === 'numbers' ? 'Your WhatsApp numbers' : tab === 'contacts' ? 'People you can reach' : tab === 'broadcasts' ? 'Send one message to many' : tab === 'team' ? 'Better, together.' : tab === 'settings' ? 'Workspace settings' : 'Let’s get you connected.'}</h1><p>{tab === 'overview' ? 'See connection health and jump into the work that matters.' : tab === 'numbers' ? 'Connect and manage your team’s sending numbers.' : tab === 'contacts' ? 'Browse the WhatsApp contacts synced with a connected number.' : tab === 'broadcasts' ? 'Create permission-based broadcasts and review delivery results.' : tab === 'team' ? 'Give the right people access to this workspace.' : tab === 'settings' ? 'A clear view of your workspace and access.' : 'From your first number to your first conversation.'}</p></div>{tab === 'numbers' && <button className="button primary" disabled={!canManage} onClick={() => open('number')}><Plus size={18}/>Connect a number</button>}{tab === 'team' && <button className="button primary" disabled={!canManage} onClick={() => open('invite')}><Plus size={18}/>Invite a teammate</button>}</div>
        {!workspaces.length && <div className="empty-state"><Users size={30}/><h2>Make room for your team</h2><p>Create your first workspace to start connecting WhatsApp numbers.</p><button className="button primary" onClick={() => open('workspace')}>Create workspace</button></div>}
        {workspaces.length > 0 && tab === 'inbox' && <InboxPanel workspaceId={active} numbers={connectedNumbers} members={members} canManage={canManage} request={request} report={setNotice}/>}
        {workspaces.length > 0 && tab === 'overview' && <>
          <div className="stat-grid"><Stat label="Total numbers" value={current.length} icon={<Smartphone size={19}/>} detail="In this workspace"/><Stat label="Connected" value={connected} icon={<Wifi size={19}/>} detail="Ready for a conversation" positive/><Stat label="Needs connection" value={current.length - connected} icon={<QrCode size={19}/>} detail={current.length - connected ? 'Pair a device to get started' : 'You’re all connected'}/><Stat label="Team members" value={members.length} icon={<Users size={19}/>} detail="Working together"/></div>
          <div className="overview-grid"><section className="numbers-panel"><div className="panel-heading"><div><h2>Connection health</h2><p>Your sending numbers and what needs attention.</p></div><button className={`icon-button ${busy ? 'spinning' : ''}`} disabled={busy} aria-label="Refresh connection status" onClick={() => run(async () => { await refresh(); })}><RefreshCw size={18}/></button></div><div className="overview-number-list">{current.slice(0, 4).map(number => <button key={number.id} onClick={() => nav('numbers')}><span className={`number-icon ${number.state !== 'open' ? 'muted' : ''}`}><MessageCircle size={20}/></span><span><strong>{number.label}</strong><small>{number.phone ?? 'WhatsApp device'}</small></span><span className={`status-badge ${number.state === 'open' ? 'online' : ''}`}><i/>{number.state === 'open' ? 'Connected' : 'Needs attention'}</span><ChevronRight size={16}/></button>)}{!current.length && <div className="empty-state compact"><Smartphone size={28}/><h3>No numbers yet</h3><p>Connect your first WhatsApp number to begin.</p></div>}</div></section><aside className="quick-actions"><h2>Quick actions</h2><button onClick={() => nav('numbers')}><span><Smartphone size={19}/></span><div><strong>Manage numbers</strong><small>Pair devices and check status</small></div><ChevronRight size={17}/></button><button onClick={() => nav('contacts')}><span><BookUser size={19}/></span><div><strong>Browse contacts</strong><small>See contacts for each number</small></div><ChevronRight size={17}/></button><button onClick={() => nav('broadcasts')}><span><Megaphone size={19}/></span><div><strong>Create broadcast</strong><small>Send to permission-based contacts</small></div><ChevronRight size={17}/></button><button onClick={() => nav('team')}><span><Users size={19}/></span><div><strong>Manage team</strong><small>Invite and review access</small></div><ChevronRight size={17}/></button></aside></div>
        </>}
        {workspaces.length > 0 && tab === 'numbers' && <>
          <section className="numbers-panel"><div className="panel-heading"><div><h2>Connected devices <span className="count-pill">{current.length}</span></h2><p>Each number has its own contacts and sending identity.</p></div><button className={`icon-button ${busy ? 'spinning' : ''}`} disabled={busy} aria-label="Refresh connection status" onClick={() => run(async () => { await refresh(); })}><RefreshCw size={18}/></button></div><div className="table-toolbar"><div className="filter-tabs" aria-label="Filter numbers">{['all', 'connected', 'offline'].map(f => <button key={f} aria-pressed={filter === f} onClick={() => setFilter(f)} className={filter === f ? 'selected' : ''}>{f === 'all' ? 'All numbers' : f === 'connected' ? 'Connected' : 'Offline'}</button>)}</div><label className="search-box"><Search size={17}/><input aria-label="Search numbers" placeholder="Search numbers…" value={query} onChange={e => setQuery(e.target.value)}/></label></div>
            <div className="number-list"><div className="table-labels"><span>NUMBER</span><span>STATUS</span><span>ACTION</span></div>{visible.map(number => <div className="number-row" key={number.id}><div className="number-info"><span className={`number-icon ${number.state !== 'open' ? 'muted' : ''}`}><MessageCircle size={22}/></span><div><strong>{number.label}</strong><span>{number.phone ?? (number.state === 'open' ? 'WhatsApp connected' : 'Not paired yet')}</span></div></div><span className={`status-badge ${number.state === 'open' ? 'online' : ''}`}><i/>{number.state === 'open' ? 'Connected' : number.state === 'connecting' ? 'Connecting' : number.error ? 'Unavailable' : 'Offline'}</span><button className="row-action" disabled={number.state !== 'open' && !canManage} onClick={() => open(number.state === 'open' ? 'message' : 'pair', number)}>{number.state === 'open' ? 'Message' : 'Connect'}{number.state === 'open' ? <ArrowUpRight size={15}/> : <QrCode size={15}/>}</button></div>)}{visible.length === 0 && <div className="empty-state compact"><Smartphone size={28}/><h3>{query || filter !== 'all' ? 'No matching numbers' : 'Your first number starts here'}</h3><p>{query || filter !== 'all' ? 'Try another search or filter.' : 'Connect a WhatsApp number and bring your team together.'}</p></div>}</div><div className="panel-footer"><ShieldCheck size={14}/>Only members of this workspace can access these numbers.</div></section>
        </>}
        {tab === 'contacts' && <section className="numbers-panel contacts-panel"><div className="panel-heading"><div><h2>WhatsApp contacts</h2><p>Select a connected number to load the contacts synced by Evolution API.</p></div></div><div className="contact-controls"><label>Connected number<select value={contactNumberId} onChange={e => { setContactNumberId(e.target.value); setContacts([]); setContactsLoaded(false); }}><option value="">Choose a number</option>{connectedNumbers.map(number => <option key={number.id} value={number.id}>{number.label}{number.phone ? ` · ${number.phone}` : ''}</option>)}</select></label><button className="button primary" disabled={!contactNumberId || busy} onClick={() => loadContacts()}>{busy ? <LoaderCircle className="spin" size={17}/> : <RefreshCw size={17}/>}Load contacts</button>{contactsLoaded && <label className="search-box contact-search"><Search size={17}/><input aria-label="Search contacts" placeholder="Search name or number…" value={contactQuery} onChange={e => setContactQuery(e.target.value)}/></label>}</div>{contactsLoaded ? <><div className="contact-summary"><strong>{contacts.length}</strong> contacts available from this number<button className="text-button" disabled={!contacts.length} onClick={() => { setSelectedContacts(contacts.map(c => c.phone)); nav('broadcasts'); }}>Select all for a broadcast</button></div><div className="contact-list">{visibleContacts.map(contact => <div className="contact-row" key={contact.phone}><span className="profile-avatar">{contact.name.slice(0, 1).toUpperCase()}</span><div><strong>{contact.name}</strong><small>+{contact.phone}</small></div><button className="row-action" onClick={() => { setSelectedContacts([contact.phone]); nav('broadcasts'); }}>Broadcast<ArrowUpRight size={15}/></button></div>)}{!visibleContacts.length && <div className="empty-state compact"><BookUser size={28}/><h3>No matching contacts</h3><p>Try a different search.</p></div>}</div></> : <div className="empty-state compact"><BookUser size={30}/><h3>{connectedNumbers.length ? 'Choose a connected number' : 'Connect a number first'}</h3><p>{connectedNumbers.length ? 'Contacts are fetched live and stay associated with that WhatsApp number.' : 'Contacts become available after a WhatsApp number is paired.'}</p></div>}</section>}
        {tab === 'broadcasts' && <CampaignsPanel workspaceId={active} numbers={connectedNumbers} syncedContacts={contacts} initialSelected={selectedContacts} canManage={canManage} onNotice={setNotice}/>}
        {tab === 'team' && <section className="numbers-panel"><div className="panel-heading"><div><h2>People in {workspace?.name}</h2><p>Owners and admins manage numbers. All members can send messages.</p></div></div>{members.map(member => <div className="member-row" key={member.user_id}><span className="profile-avatar">{member.email.slice(0, 1).toUpperCase()}</span><div><strong>{member.email}</strong><small>Joined {new Date(member.joined_at).toLocaleDateString('en-GB')}</small></div><span className="role-badge">{member.role}</span>{workspace?.role === 'owner' && member.role !== 'owner' && <button className="text-button" disabled={busy} onClick={() => run(async () => { await request('/api/team', { action: 'remove', workspaceId: active, userId: member.user_id }); await refresh(); })}>Remove</button>}</div>)}{!members.length && <div className="empty-state compact">No members to show.</div>}</section>}
        {tab === 'settings' && <section className="settings-panel"><h2>Workspace details</h2><dl><div><dt>Workspace name</dt><dd>{workspace?.name}</dd></div><div><dt>Your access</dt><dd className="capitalize">{workspace?.role}</dd></div><div><dt>Account</dt><dd>{initial.user.email}</dd></div><div><dt>Environment</dt><dd>Live workspace</dd></div></dl><div className="info-box"><ShieldCheck size={22}/><p>Your team’s numbers belong to this workspace. Switching workspaces changes which numbers and team members you can access.</p></div></section>}
        {tab === 'help' && <section className="help-grid">{[{ n: '01', title: 'Create a workspace', text: 'Give each business or team its own workspace. Switch between them using the menu on the left.' }, { n: '02', title: 'Connect WhatsApp', text: 'Add a number, then generate a QR code. On your phone, open WhatsApp → Settings → Linked devices → Link a device. Scan the code using another screen.' }, { n: '03', title: 'Invite your team', text: 'Create an invitation for a teammate’s email. Share the link with them. They must sign in using that email to join.' }, { n: '04', title: 'Start a conversation', text: 'Choose Message beside a connected number. Enter a recipient’s international number and send an individual message.' }].map(step => <article key={step.n}><span>{step.n}</span><h2>{step.title}</h2><p>{step.text}</p></article>)}</section>}
        <footer className="page-footer"><span><span className="footer-dot"/>A little clarity for every conversation.</span><span>V Connect</span></footer>
      </main>
    </div>
    {modal && <Dialog title={modal === 'number' ? 'Connect a WhatsApp number' : modal === 'workspace' ? 'Create a workspace' : modal === 'invite' ? 'Invite a teammate' : modal === 'pair' ? `Connect ${selected?.label}` : `Message from ${selected?.label}`} onClose={() => !busy && setModal(null)}>
      {modal === 'pair' ? <div className="pair-content"><p>On your phone, open <strong>WhatsApp → Linked devices → Link a device</strong>, then scan this code from another screen.</p>{qr ? <><img className="qr-image" src={qr} alt="WhatsApp device pairing QR code"/><p className="muted-text">Codes expire quickly. Generate a new one if needed.</p></> : <div className="qr-placeholder"><QrCode size={64}/><span>Your pairing code will appear here</span></div>}<button className="button primary full" disabled={busy} onClick={pair}>{busy ? <LoaderCircle className="spin" size={18}/> : <RefreshCw size={17}/>} {qr ? 'Generate a new code' : 'Generate QR code'}</button><button className="button secondary full" disabled={busy} onClick={() => run(async () => { await refresh(); setModal(null); })}>I’ve scanned the code</button></div> : <form onSubmit={submit} className="modal-form">
        {modal === 'number' && <><p>Give this number a name your team will recognize. You’ll pair it with WhatsApp next.</p><label>Number name<input name="label" required maxLength={60} placeholder="e.g. Customer support" autoFocus/></label></>}
        {modal === 'workspace' && <><p>A separate space for your business, its numbers, and its people.</p><label>Workspace name<input name="name" required minLength={2} maxLength={60} placeholder="e.g. VCGL Engineering" autoFocus/></label></>}
        {modal === 'invite' && <><p>The invitation works only for this email and expires in seven days.</p><label>Email address<input name="email" type="email" required placeholder="teammate@company.com" autoFocus/></label><label>Role<select name="role"><option value="member">Member · send messages</option><option value="admin">Admin · manage numbers and invitations</option></select></label>{invite && <div className="invite-result"><input aria-label="Invitation link" readOnly value={invite}/><button type="button" className="button secondary" onClick={() => run(async () => { await navigator.clipboard.writeText(invite); setNotice('Invitation link copied.'); })}><Copy size={16}/>Copy link</button></div>}</>}
        {modal === 'message' && <><p>Send a message, photo, video, audio, or document.</p><label>Recipient number<div className="phone-field"><select name="countryCode" aria-label="Country code">{countryCodes.map(country=><option key={country.code} value={country.code}>{country.flag} +{country.code}</option>)}</select><input name="phone" type="tel" required minLength={7} maxLength={24} placeholder="0801 234 5678" autoFocus/></div><small>Enter the local number. We’ll add the selected country code.</small></label><label>Message or caption<textarea name="text" maxLength={4000} rows={5} placeholder="Write an optional caption…"/></label><label className="media-picker"><span><Paperclip size={17}/>Attach media</span><input name="media" type="file" accept={mediaAccept}/><small>Photo, video, audio, PDF, Word, Excel, CSV or text · up to 16 MB</small></label></>}
        <button className="button primary full" disabled={busy}>{busy ? <LoaderCircle size={18} className="spin"/> : modal === 'message' ? <Send size={17}/> : <Plus size={17}/>} {modal === 'number' ? 'Add number' : modal === 'workspace' ? 'Create workspace' : modal === 'invite' ? 'Create invitation link' : 'Send message'}</button>
      </form>}{notice && <div className="modal-notice" role="status">{notice}</div>}
    </Dialog>}
  </div>;
}
function Stat({ label, value, icon, detail, positive }: { label: string; value: number; icon: ReactNode; detail: string; positive?: boolean }) { return <div className="stat-card"><div><span>{label}</span><span className={`stat-icon ${positive ? 'positive' : ''}`}>{icon}</span></div><strong>{value.toString().padStart(2, '0')}</strong><small>{positive && <span className="small-dot"/>}{detail}</small></div>; }
function Dialog({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => { dialog?.close(); }; }, []);
  return <dialog ref={ref} className="dialog" onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="dialog-inner"><div className="dialog-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={21}/></button></div>{children}</div></dialog>;
}
