'use client';
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownLeft, ArrowUpRight, Check, ChevronDown, ChevronRight, CircleHelp, Copy, ExternalLink, LayoutGrid, LoaderCircle, LogOut, Menu, MessageCircle, Plus, QrCode, RefreshCw, Search, Send, Settings2, ShieldCheck, Smartphone, Users, Wifi, X } from 'lucide-react';
import type { DashboardData, Member, WhatsAppNumber, Workspace } from '@/lib/types';

type Modal = 'number' | 'workspace' | 'invite' | 'pair' | 'message' | null;
export function Dashboard({ initial }: { initial: DashboardData }) {
  const [workspaces, setWorkspaces] = useState(initial.workspaces);
  const [active, setActive] = useState(initial.workspaces[0]?.id ?? '');
  const [numbers, setNumbers] = useState(initial.numbers);
  const [members, setMembers] = useState(initial.members);
  const [tab, setTab] = useState('overview');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [modal, setModal] = useState<Modal>(null);
  const [selected, setSelected] = useState<WhatsAppNumber | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState(initial.error ?? '');
  const [qr, setQr] = useState('');
  const [invite, setInvite] = useState('');
  const [mobileOpen, setMobileOpen] = useState(false);
  const workspace = workspaces.find(w => w.id === active);
  const canManage = workspace?.role === 'owner' || workspace?.role === 'admin';
  const current = numbers.filter(n => n.workspace_id === active);
  const connected = current.filter(n => n.state === 'open').length;
  const visible = current.filter(n => `${n.label} ${n.phone ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'connected' ? n.state === 'open' : n.state !== 'open')));
  const activeRef = useRef(active);
  activeRef.current = active;
  async function request(path: string, body?: unknown) {
    const response = await fetch(path, { method: body ? 'POST' : 'GET', headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined });
    const data = await response.json();
    if (!response.ok) throw new Error(data.error ?? 'Something went wrong. Please try again.');
    return data;
  }
  async function refresh(workspaceId = active) {
    if (initial.demo || !workspaceId) return;
    const data = await request(`/api/workspaces?id=${encodeURIComponent(workspaceId)}`);
    if (activeRef.current !== workspaceId) return;
    setNumbers(prev => [...prev.filter(n => n.workspace_id !== workspaceId), ...data.numbers]);
    setMembers(data.members);
    if (data.warning) setNotice(data.warning);
  }
  useEffect(() => { if (!initial.demo && active) { setMembers([]); refresh(active).catch(e => setNotice(e.message)); } }, [active]); // eslint-disable-line react-hooks/exhaustive-deps
  async function run(action: () => Promise<void>) { setBusy(true); setNotice(''); try { await action(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Please try again.'); } finally { setBusy(false); } }
  function open(next: Modal, number?: WhatsAppNumber) { setSelected(number ?? null); setQr(''); setInvite(''); setModal(next); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const fields = Object.fromEntries(new FormData(event.currentTarget));
    await run(async () => {
      if (initial.demo) {
        if (modal === 'number') setNumbers(prev => [...prev, { id: crypto.randomUUID(), workspace_id: active, label: String(fields.label), instance_name: 'demo', created_at: new Date().toISOString(), state: 'close' }]);
        if (modal === 'workspace') { const id = crypto.randomUUID(); setWorkspaces(prev => [...prev, { id, name: String(fields.name), role: 'owner' }]); setActive(id); }
        setModal(null); setNotice(modal === 'message' ? 'Demo only — no message was sent.' : modal === 'invite' ? 'Demo only — no invitation was created.' : 'Demo updated. Changes last until you reload.'); return;
      }
      if (modal === 'workspace') { const data = await request('/api/workspaces', { name: fields.name }); setWorkspaces(prev => [...prev, data.workspace]); setActive(data.workspace.id); }
      if (modal === 'number') { const data = await request('/api/numbers', { action: 'create', workspaceId: active, label: fields.label }); await refresh(); if (data.warning) setNotice(data.warning); }
      if (modal === 'invite') { const data = await request('/api/team', { action: 'invite', workspaceId: active, email: fields.email, role: fields.role }); setInvite(`${window.location.origin}/invite?token=${data.token}`); return; }
      if (modal === 'message') { await request('/api/numbers', { action: 'send', workspaceId: active, numberId: selected?.id, phone: fields.phone, text: fields.text }); setNotice('Message accepted by WhatsApp.'); }
      setModal(null);
    });
  }
  async function pair() { await run(async () => { if (initial.demo) { setNotice('Pairing needs a live workspace. Demo numbers cannot connect to WhatsApp.'); return; } const data = await request('/api/numbers', { action: 'connect', workspaceId: active, numberId: selected?.id }); if (data.base64) setQr(data.base64); else setNotice(data.connected ? 'This number is already connected. Close this panel and refresh.' : 'QR code is preparing. Try again in a few seconds.'); }); }
  function nav(name: string) { setTab(name); setMobileOpen(false); setQuery(''); }
  return <div className="app-shell">
    {mobileOpen && <button className="mobile-overlay" aria-label="Close menu" onClick={() => setMobileOpen(false)} />}
    <aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}>
      <a href="/" className="brand"><span className="brand-icon"><MessageCircle size={23} strokeWidth={2.5}/></span>v connect<span className="brand-dot">.</span></a>
      <div className="workspace-picker"><span className="workspace-avatar">{workspace?.name.slice(0, 1) ?? 'W'}</span><label><span className="eyebrow">WORKSPACE</span><select aria-label="Current workspace" value={active} onChange={e => setActive(e.target.value)}>{workspaces.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}{!workspaces.length && <option value="">Create a workspace</option>}</select></label><ChevronDown size={15}/></div>
      <div className="nav-label">WORKSPACE</div>
      <nav aria-label="Main navigation">{[{ id: 'overview', label: 'Overview', icon: LayoutGrid }, { id: 'numbers', label: 'WhatsApp numbers', icon: Smartphone }, { id: 'team', label: 'Team members', icon: Users }, { id: 'settings', label: 'Settings', icon: Settings2 }].map(item => <button key={item.id} className={`nav-item ${tab === item.id ? 'active' : ''}`} onClick={() => nav(item.id)}><item.icon size={19}/>{item.label}{item.id === 'numbers' && <span className="nav-count">{current.length}</span>}</button>)}</nav>
      <button className="new-workspace" onClick={() => open('workspace')}><Plus size={17}/>Create workspace</button>
      <div className="sidebar-bottom"><div className="privacy-card"><ShieldCheck size={21}/><strong>Your workspace, private.</strong><p>Numbers and access stay separate across your teams.</p></div><button className="help-link" onClick={() => nav('help')}><CircleHelp size={18}/>Help & getting started<ArrowUpRight size={15}/></button><div className="profile"><span className="profile-avatar">{initial.user.email.slice(0, 1).toUpperCase()}</span><span><strong>{initial.demo ? 'Alex Morgan' : initial.user.email.split('@')[0]}</strong><small>{workspace?.role ?? 'Workspace member'}</small></span>{!initial.demo && <button className="icon-button" aria-label="Sign out" onClick={() => run(async () => { await request('/api/auth', { action: 'signout' }); window.location.href = '/login'; })}><LogOut size={17}/></button>}</div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={22}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{tab === 'numbers' ? 'WhatsApp numbers' : tab === 'team' ? 'Team members' : tab === 'help' ? 'Getting started' : tab === 'settings' ? 'Settings' : 'Overview'}</strong></div><div className="topbar-right"><span className="private-label"><ShieldCheck size={15}/>Private workspace</span><span className="mini-avatar">{initial.user.email.slice(0, 1).toUpperCase()}</span></div></header>
      <main id="main-content">
        {initial.demo && <div className="demo-banner"><span><span className="demo-tag">DEMO</span>Explore a sample workspace. No real numbers or messages.</span><a href="/login">Connect your workspace<ArrowUpRight size={14}/></a></div>}
        {notice && <div className="notice" role="status"><span>{notice}</span><button className="icon-button" aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={17}/></button></div>}
        <div className="page-heading"><div><div className="section-kicker">{workspace?.name ?? 'YOUR WORKSPACE'}</div><h1>{tab === 'overview' ? 'A little more connected.' : tab === 'numbers' ? 'Your WhatsApp numbers' : tab === 'team' ? 'Better, together.' : tab === 'settings' ? 'Workspace settings' : 'Let’s get you connected.'}</h1><p>{tab === 'overview' ? 'All your numbers. One place to keep things moving.' : tab === 'numbers' ? 'Connect, manage, and message from your team’s numbers.' : tab === 'team' ? 'Give the right people access to this workspace.' : tab === 'settings' ? 'A clear view of your workspace and access.' : 'From your first number to your first conversation.'}</p></div>{(tab === 'overview' || tab === 'numbers') && <button className="button primary" disabled={!canManage} onClick={() => open('number')}><Plus size={18}/>Connect a number</button>}{tab === 'team' && <button className="button primary" disabled={!canManage} onClick={() => open('invite')}><Plus size={18}/>Invite a teammate</button>}</div>
        {!workspaces.length && <div className="empty-state"><Users size={30}/><h2>Make room for your team</h2><p>Create your first workspace to start connecting WhatsApp numbers.</p><button className="button primary" onClick={() => open('workspace')}>Create workspace</button></div>}
        {workspaces.length > 0 && (tab === 'overview' || tab === 'numbers') && <>
          <div className="stat-grid"><Stat label="Total numbers" value={current.length} icon={<Smartphone size={19}/>} detail="In this workspace"/><Stat label="Connected" value={connected} icon={<Wifi size={19}/>} detail="Ready for a conversation" positive/><Stat label="Needs connection" value={current.length - connected} icon={<QrCode size={19}/>} detail={current.length - connected ? 'Pair a device to get started' : 'You’re all connected'}/><Stat label="Team members" value={members.length} icon={<Users size={19}/>} detail="Working together"/></div>
          <div className="content-grid"><section className="numbers-panel"><div className="panel-heading"><div><h2>WhatsApp numbers <span className="count-pill">{current.length}</span></h2><p>A home for every conversation.</p></div><button className={`icon-button ${busy ? 'spinning' : ''}`} disabled={busy} aria-label="Refresh connection status" onClick={() => run(async () => { await refresh(); if (initial.demo) setNotice('Demo connection statuses are examples.'); })}><RefreshCw size={18}/></button></div><div className="table-toolbar"><div className="filter-tabs" aria-label="Filter numbers">{['all', 'connected', 'offline'].map(f => <button key={f} aria-pressed={filter === f} onClick={() => setFilter(f)} className={filter === f ? 'selected' : ''}>{f === 'all' ? 'All numbers' : f === 'connected' ? 'Connected' : 'Offline'}</button>)}</div><label className="search-box"><Search size={17}/><input aria-label="Search numbers" placeholder="Search numbers…" value={query} onChange={e => setQuery(e.target.value)}/></label></div>
            <div className="number-list"><div className="table-labels"><span>NUMBER</span><span>STATUS</span><span>ACTION</span></div>{visible.map(number => <div className="number-row" key={number.id}><div className="number-info"><span className={`number-icon ${number.state !== 'open' ? 'muted' : ''}`}><MessageCircle size={22}/></span><div><strong>{number.label}</strong><span>{number.phone ?? (number.state === 'open' ? 'WhatsApp connected' : 'Not paired yet')}</span></div></div><span className={`status-badge ${number.state === 'open' ? 'online' : ''}`}><i/>{number.state === 'open' ? 'Connected' : number.state === 'connecting' ? 'Connecting' : number.error ? 'Unavailable' : 'Offline'}</span><button className="row-action" disabled={number.state !== 'open' && !canManage} onClick={() => open(number.state === 'open' ? 'message' : 'pair', number)}>{number.state === 'open' ? 'Message' : 'Connect'}{number.state === 'open' ? <ArrowUpRight size={15}/> : <QrCode size={15}/>}</button></div>)}{visible.length === 0 && <div className="empty-state compact"><Smartphone size={28}/><h3>{query || filter !== 'all' ? 'No matching numbers' : 'Your first number starts here'}</h3><p>{query || filter !== 'all' ? 'Try another search or filter.' : 'Connect a WhatsApp number and bring your team together.'}</p></div>}</div><div className="panel-footer"><ShieldCheck size={14}/>Only members of this workspace can access these numbers.</div></section>
            <aside className="right-column"><section className="connect-card"><span className="connect-card-icon"><MessageCircle size={26}/><Plus size={13}/></span><div className="section-kicker">ROOM TO GROW</div><h2>One team.<br/>More connections.</h2><p>Keep sales, support, and project conversations on their own numbers.</p><button disabled={!canManage} onClick={() => open('number')}>Add another number<ArrowUpRight size={17}/></button><div className="line-decoration" aria-hidden="true"/></section><section className="checklist"><h3>Make yourself at home</h3><button onClick={() => open('workspace')}><span className="check-step done"><Check size={13}/></span><span>Create your workspace</span><ChevronRight size={14}/></button><button onClick={() => canManage && open('number')}><span className={`check-step ${connected ? 'done' : ''}`}>{connected ? <Check size={13}/> : '2'}</span><span>Connect a number</span><ChevronRight size={14}/></button><button onClick={() => nav('team')}><span className={`check-step ${members.length > 1 ? 'done' : ''}`}>{members.length > 1 ? <Check size={13}/> : '3'}</span><span>Bring your team along</span><ChevronRight size={14}/></button></section></aside></div>
        </>}
        {tab === 'team' && <section className="numbers-panel"><div className="panel-heading"><div><h2>People in {workspace?.name}</h2><p>Owners and admins manage numbers. All members can send messages.</p></div></div>{members.map(member => <div className="member-row" key={member.user_id}><span className="profile-avatar">{member.email.slice(0, 1).toUpperCase()}</span><div><strong>{member.email}</strong><small>Joined {new Date(member.joined_at).toLocaleDateString('en-GB')}</small></div><span className="role-badge">{member.role}</span>{workspace?.role === 'owner' && member.role !== 'owner' && <button className="text-button" disabled={busy} onClick={() => run(async () => { if (initial.demo) { setMembers(prev => prev.filter(m => m.user_id !== member.user_id)); return; } await request('/api/team', { action: 'remove', workspaceId: active, userId: member.user_id }); await refresh(); })}>Remove</button>}</div>)}{!members.length && <div className="empty-state compact">No members to show.</div>}</section>}
        {tab === 'settings' && <section className="settings-panel"><h2>Workspace details</h2><dl><div><dt>Workspace name</dt><dd>{workspace?.name}</dd></div><div><dt>Your access</dt><dd className="capitalize">{workspace?.role}</dd></div><div><dt>Account</dt><dd>{initial.user.email}</dd></div><div><dt>Environment</dt><dd>{initial.demo ? 'Demo · sample data' : 'Live workspace'}</dd></div></dl><div className="info-box"><ShieldCheck size={22}/><p>Your team’s numbers belong to this workspace. Switching workspaces changes which numbers and team members you can access.</p></div></section>}
        {tab === 'help' && <section className="help-grid">{[{ n: '01', title: 'Create a workspace', text: 'Give each business or team its own workspace. Switch between them using the menu on the left.' }, { n: '02', title: 'Connect WhatsApp', text: 'Add a number, then generate a QR code. On your phone, open WhatsApp → Settings → Linked devices → Link a device. Scan the code using another screen.' }, { n: '03', title: 'Invite your team', text: 'Create an invitation for a teammate’s email. Share the link with them. They must sign in using that email to join.' }, { n: '04', title: 'Start a conversation', text: 'Choose Message beside a connected number. Enter a recipient’s international number and send an individual message.' }].map(step => <article key={step.n}><span>{step.n}</span><h2>{step.title}</h2><p>{step.text}</p></article>)}</section>}
        <footer className="page-footer"><span><span className="footer-dot"/>A little clarity for every conversation.</span><span>V Connect</span></footer>
      </main>
    </div>
    {modal && <Dialog title={modal === 'number' ? 'Connect a WhatsApp number' : modal === 'workspace' ? 'Create a workspace' : modal === 'invite' ? 'Invite a teammate' : modal === 'pair' ? `Connect ${selected?.label}` : `Message from ${selected?.label}`} onClose={() => !busy && setModal(null)}>
      {modal === 'pair' ? <div className="pair-content"><p>On your phone, open <strong>WhatsApp → Linked devices → Link a device</strong>, then scan this code from another screen.</p>{qr ? <><img className="qr-image" src={qr} alt="WhatsApp device pairing QR code"/><p className="muted-text">Codes expire quickly. Generate a new one if needed.</p></> : <div className="qr-placeholder"><QrCode size={64}/><span>Your pairing code will appear here</span></div>}<button className="button primary full" disabled={busy} onClick={pair}>{busy ? <LoaderCircle className="spin" size={18}/> : <RefreshCw size={17}/>} {qr ? 'Generate a new code' : 'Generate QR code'}</button><button className="button secondary full" disabled={busy} onClick={() => run(async () => { await refresh(); setModal(null); })}>I’ve scanned the code</button></div> : <form onSubmit={submit} className="modal-form">
        {modal === 'number' && <><p>Give this number a name your team will recognize. You’ll pair it with WhatsApp next.</p><label>Number name<input name="label" required maxLength={60} placeholder="e.g. Customer support" autoFocus/></label></>}
        {modal === 'workspace' && <><p>A separate space for your business, its numbers, and its people.</p><label>Workspace name<input name="name" required minLength={2} maxLength={60} placeholder="e.g. VCGL Engineering" autoFocus/></label></>}
        {modal === 'invite' && <><p>The invitation works only for this email and expires in seven days.</p><label>Email address<input name="email" type="email" required placeholder="teammate@company.com" autoFocus/></label><label>Role<select name="role"><option value="member">Member · send messages</option><option value="admin">Admin · manage numbers and invitations</option></select></label>{invite && <div className="invite-result"><input aria-label="Invitation link" readOnly value={invite}/><button type="button" className="button secondary" onClick={() => run(async () => { await navigator.clipboard.writeText(invite); setNotice('Invitation link copied.'); })}><Copy size={16}/>Copy link</button></div>}</>}
        {modal === 'message' && <><p>Send an individual WhatsApp message from this workspace’s number.</p><label>Recipient number<input name="phone" type="tel" required pattern="\+?[1-9][0-9]{7,14}" placeholder="+2348012345678" autoFocus/><small>Include the country code, without spaces.</small></label><label>Message<textarea name="text" required maxLength={4000} rows={5} placeholder="Write your message…"/></label></>}
        <button className="button primary full" disabled={busy}>{busy ? <LoaderCircle size={18} className="spin"/> : modal === 'message' ? <Send size={17}/> : <Plus size={17}/>} {modal === 'number' ? 'Add number' : modal === 'workspace' ? 'Create workspace' : modal === 'invite' ? 'Create invitation link' : initial.demo ? 'Try sending in demo' : 'Send message'}</button>
      </form>}{notice && <div className="modal-notice" role="status">{notice}</div>}
    </Dialog>}
  </div>;
}
function Stat({ label, value, icon, detail, positive }: { label: string; value: number; icon: ReactNode; detail: string; positive?: boolean }) { return <div className="stat-card"><div><span>{label}</span><span className={`stat-icon ${positive ? 'positive' : ''}`}>{icon}</span></div><strong>{value.toString().padStart(2, '0')}</strong><small>{positive && <span className="small-dot"/>}{detail}</small></div>; }
function Dialog({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => { dialog?.close(); }; }, []);
  return <dialog ref={ref} className="dialog" onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="dialog-inner"><div className="dialog-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={21}/></button></div>{children}</div></dialog>;
}
