'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, Inbox, LoaderCircle, MessageCircle, RefreshCw, Search, Send, Users } from 'lucide-react';
import type { ConversationNote, InboxChat, InboxMessage, Member, WhatsAppNumber } from '@/lib/types';
import { supabaseBrowser } from '@/lib/supabase/client';

export function InboxPanel({ workspaceId, numbers, members, canManage, request, report }: { workspaceId: string; numbers: WhatsAppNumber[]; members: Member[]; canManage: boolean; request: (path: string, body?: unknown) => Promise<any>; report: (message: string) => void }) {
  const [numberId, setNumberId] = useState(numbers[0]?.id ?? ''), [chats, setChats] = useState<InboxChat[]>([]), [messages, setMessages] = useState<InboxMessage[]>([]), [selected, setSelected] = useState<InboxChat | null>(null), [query, setQuery] = useState(''), [busy, setBusy] = useState(false);
  const [notes, setNotes] = useState<ConversationNote[]>([]);
  const messageEnd = useRef<HTMLDivElement>(null);
  const visible = chats.filter(chat => `${chat.name} ${chat.id}`.toLowerCase().includes(query.toLowerCase()));
  async function loadChats() { if (!numberId) return; setBusy(true); try { const data = await request(`/api/inbox?workspaceId=${encodeURIComponent(workspaceId)}&numberId=${encodeURIComponent(numberId)}`); setChats(data.chats); } catch (error) { report(error instanceof Error ? error.message : 'Could not load conversations.'); } finally { setBusy(false); } }
  async function openChat(chat: InboxChat) { setSelected(chat); setMessages([]); setBusy(true); try { const data = await request(`/api/inbox?workspaceId=${encodeURIComponent(workspaceId)}&numberId=${encodeURIComponent(numberId)}&remoteJid=${encodeURIComponent(chat.id)}`); setMessages(data.messages); setNotes(data.notes ?? []); if (data.conversation) setSelected(current => current ? { ...current, status: data.conversation.status, assigned_to: data.conversation.assigned_to } : current); requestAnimationFrame(() => messageEnd.current?.scrollIntoView()); } catch (error) { report(error instanceof Error ? error.message : 'Could not load messages.'); } finally { setBusy(false); } }
  useEffect(() => { setSelected(null); setChats([]); setMessages([]); if (numberId) loadChats(); }, [numberId, workspaceId]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!numberId) return; const channel = supabaseBrowser().channel(`inbox:${numberId}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'vc_inbox_events', filter: `number_id=eq.${numberId}` }, () => { loadChats(); if (selected) openChat(selected); }).subscribe(); return () => { supabaseBrowser().removeChannel(channel); }; }, [numberId, selected?.id]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!numberId || !canManage) return; request('/api/inbox/realtime', { workspaceId, numberId }).catch(() => { /* Manual refresh remains available until deployed configuration is ready. */ }); }, [numberId, workspaceId, canManage]); // eslint-disable-line react-hooks/exhaustive-deps
  async function reply(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = event.currentTarget; const text = String(new FormData(form).get('text') ?? '').trim(); if (!text) return; setBusy(true); try { await request('/api/inbox', { workspaceId, numberId, remoteJid: selected.id, text }); form.reset(); await openChat(selected); } catch (error) { report(error instanceof Error ? error.message : 'Could not send the reply.'); } finally { setBusy(false); } }
  async function updateConversation(status: 'open'|'pending'|'resolved', assignedTo: string|null) { if (!selected) return; try { await request('/api/inbox', { action:'update', workspaceId, numberId, remoteJid:selected.id, status, assignedTo }); setSelected({ ...selected, status, assigned_to:assignedTo }); await loadChats(); } catch(error) { report(error instanceof Error ? error.message : 'Could not update conversation.'); } }
  async function addNote(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if(!selected)return; const form=event.currentTarget; const text=String(new FormData(form).get('note')??'').trim(); if(!text)return; try { const data=await request('/api/inbox',{action:'note',workspaceId,numberId,remoteJid:selected.id,text}); setNotes(current=>[...current,data.note]); form.reset(); } catch(error){report(error instanceof Error?error.message:'Could not add note.');} }
  return <section className={`inbox-shell ${selected ? 'chat-open' : ''}`}>
    <aside className="inbox-list"><div className="inbox-list-head"><div><h2>Inbox</h2><p>{chats.length} conversations</p></div><button className={`icon-button ${busy ? 'spinning' : ''}`} disabled={busy||!numberId} onClick={loadChats}><RefreshCw size={18}/></button></div><label className="inbox-number">Inbox for<select value={numberId} onChange={e=>setNumberId(e.target.value)}><option value="">Choose a connected number</option>{numbers.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label className="search-box inbox-search"><Search size={17}/><input placeholder="Search conversations…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="chat-list">{visible.map(chat=><button key={chat.id} className={selected?.id===chat.id?'active':''} onClick={()=>openChat(chat)}><span className={`chat-avatar ${chat.group?'group':''}`}>{chat.group?<Users size={18}/>:chat.name[0]?.toUpperCase()}</span><span><strong>{chat.name}</strong><small>{chat.preview}</small></span><span className="chat-meta">{chat.status??'open'}{(chat.unread_count??chat.unread)>0&&<i>{chat.unread_count??chat.unread}</i>}</span></button>)}{!busy&&numberId&&!visible.length&&<div className="inbox-empty"><Inbox size={27}/><strong>No conversations found</strong><span>New WhatsApp chats will appear here.</span></div>}</div></aside>
    <div className="conversation"><header>{selected&&<><button className="icon-button inbox-back" onClick={()=>setSelected(null)}><ArrowLeft size={20}/></button><span className={`chat-avatar ${selected.group?'group':''}`}>{selected.group?<Users size={18}/>:selected.name[0]?.toUpperCase()}</span><div className="conversation-person"><strong>{selected.name}</strong><small>{selected.group?'WhatsApp group':`+${selected.id.split('@')[0]}`}</small></div><div className="conversation-actions"><select aria-label="Conversation status" value={selected.status??'open'} onChange={e=>updateConversation(e.target.value as 'open'|'pending'|'resolved',selected.assigned_to??null)}><option value="open">Open</option><option value="pending">Pending</option><option value="resolved">Resolved</option></select><select aria-label="Assigned teammate" value={selected.assigned_to??''} onChange={e=>updateConversation(selected.status??'open',e.target.value||null)}><option value="">Unassigned</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.email}</option>)}</select></div></>}</header>{selected?<><div className="message-stream"><div className="internal-notes"><strong>Team notes</strong>{notes.map(note=><p key={note.id}>{note.body}<small>{members.find(m=>m.user_id===note.author_id)?.email??'Teammate'} · {new Date(note.created_at).toLocaleString('en-GB')}</small></p>)}<form onSubmit={addNote}><input name="note" maxLength={2000} placeholder="Add a private note…"/><button>Add note</button></form></div>{messages.map(message=><div key={message.id} className={`message-bubble ${message.fromMe?'mine':''}`}><p>{message.text}</p><small>{message.timestamp?new Date(message.timestamp*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</small></div>)}{busy&&!messages.length&&<LoaderCircle className="spin conversation-loader" size={25}/>}<div ref={messageEnd}/></div><form className="reply-box" onSubmit={reply}><input name="text" required maxLength={4000} placeholder="Write a reply…"/><button disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Send size={18}/>}</button></form></>:<div className="conversation-placeholder"><span className="inbox-hero-icon"><MessageCircle size={34}/></span><strong>Your conversations live here</strong><span>Choose a chat to read messages and reply.</span></div>}</div>
  </section>;
}
