create table public.vc_conversations (id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.vc_workspaces on delete cascade,number_id uuid not null references public.vc_numbers on delete cascade,remote_jid text not null,status text not null default 'open' check(status in('open','pending','resolved')),assigned_to uuid references auth.users on delete set null,unread_count int not null default 0 check(unread_count>=0),last_message_at timestamptz,updated_at timestamptz not null default now(),unique(number_id,remote_jid));
create table public.vc_conversation_notes (id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.vc_conversations on delete cascade,workspace_id uuid not null references public.vc_workspaces on delete cascade,author_id uuid not null references auth.users on delete restrict,body text not null check(char_length(body) between 1 and 2000),created_at timestamptz not null default now());
alter table public.vc_conversations enable row level security; alter table public.vc_conversation_notes enable row level security;
create policy vc_conversations_read on public.vc_conversations for select to authenticated using(public.vc_role(workspace_id) is not null);
create policy vc_notes_read on public.vc_conversation_notes for select to authenticated using(public.vc_role(workspace_id) is not null);
revoke all on public.vc_conversations,public.vc_conversation_notes from anon,authenticated; grant select on public.vc_conversations,public.vc_conversation_notes to authenticated;
drop function public.vc_record_inbox_event(text,text,text);
create function public.vc_record_inbox_event(webhook_secret text,provider_instance text,event_name text,conversation_jid text default null,sent_by_us boolean default false) returns void language plpgsql security definer set search_path='' as $$ declare w uuid;n_id uuid; begin
if event_name not in('messages.upsert','messages.update','send.message','send.message.update','chats.upsert','chats.update','connection.update') then return; end if;
select c.workspace_id,c.number_id into w,n_id from public.vc_webhook_configs c join public.vc_numbers n on n.id=c.number_id where n.instance_name=provider_instance and c.secret=webhook_secret;if n_id is null then raise exception 'Invalid webhook secret';end if;
insert into public.vc_inbox_events(workspace_id,number_id,event) values(w,n_id,event_name);
if conversation_jid is not null and conversation_jid ~ '^([1-9][0-9]{7,14}@s\.whatsapp\.net|[0-9-]{8,40}@g\.us)$' then insert into public.vc_conversations(workspace_id,number_id,remote_jid,unread_count,last_message_at) values(w,n_id,conversation_jid,case when sent_by_us then 0 else 1 end,now()) on conflict(number_id,remote_jid) do update set unread_count=case when sent_by_us then public.vc_conversations.unread_count else public.vc_conversations.unread_count+1 end,last_message_at=now(),updated_at=now();end if;end $$;
create function public.vc_update_conversation(target uuid,source_number uuid,conversation_jid text,next_status text,assignee uuid) returns public.vc_conversations language plpgsql security definer set search_path='' as $$ declare r public.vc_conversations;begin if public.vc_role(target) is null or next_status not in('open','pending','resolved') then raise exception 'Invalid conversation';end if;if assignee is not null and not exists(select 1 from public.vc_memberships where workspace_id=target and user_id=assignee)then raise exception 'Invalid assignee';end if;insert into public.vc_conversations(workspace_id,number_id,remote_jid,status,assigned_to)values(target,source_number,conversation_jid,next_status,assignee)on conflict(number_id,remote_jid)do update set status=excluded.status,assigned_to=excluded.assigned_to,updated_at=now() returning * into r;return r;end $$;
create function public.vc_mark_conversation_read(target uuid,source_number uuid,conversation_jid text)returns void language plpgsql security definer set search_path='' as $$ begin if public.vc_role(target)is null then raise exception 'Denied';end if;update public.vc_conversations set unread_count=0 where workspace_id=target and number_id=source_number and remote_jid=conversation_jid;end $$;
create function public.vc_add_conversation_note(target uuid,source_number uuid,conversation_jid text,note_body text)returns public.vc_conversation_notes language plpgsql security definer set search_path='' as $$ declare c uuid;r public.vc_conversation_notes;begin if public.vc_role(target)is null or char_length(trim(note_body))not between 1 and 2000 then raise exception 'Invalid note';end if;insert into public.vc_conversations(workspace_id,number_id,remote_jid)values(target,source_number,conversation_jid)on conflict(number_id,remote_jid)do nothing;select id into c from public.vc_conversations where workspace_id=target and number_id=source_number and remote_jid=conversation_jid;insert into public.vc_conversation_notes(conversation_id,workspace_id,author_id,body)values(c,target,auth.uid(),trim(note_body))returning * into r;return r;end $$;
revoke all on function public.vc_record_inbox_event(text,text,text,text,boolean),public.vc_update_conversation(uuid,uuid,text,text,uuid),public.vc_mark_conversation_read(uuid,uuid,text),public.vc_add_conversation_note(uuid,uuid,text,text)from public;
grant execute on function public.vc_record_inbox_event(text,text,text,text,boolean)to anon;grant execute on function public.vc_update_conversation(uuid,uuid,text,text,uuid),public.vc_mark_conversation_read(uuid,uuid,text),public.vc_add_conversation_note(uuid,uuid,text,text)to authenticated;
alter publication supabase_realtime add table public.vc_conversations;alter publication supabase_realtime add table public.vc_conversation_notes;
